
export const FIND_ENTITY_URL = 'FIND_ENTITY_URL';
export const FIND_ENTITY_URL_SUCCESS = 'FIND_ENTITY_URL_SUCCESS';
export const FIND_ENTITY_URL_ERROR = 'FIND_ENTITY_URL_ERROR';

export const FIND_ALL = 'FIND_ALL';
export const FIND_ALL_SUCCESS = 'FIND_ALL_SUCCESS';
export const FIND_ALL_ERROR = 'FIND_ALL_ERROR';

export const GET_WIKIPEDIA_CONTENT = 'GET_WIKIPEDIA_CONTENT';
export const GET_WIKIPEDIA_CONTENT_SUCCESS = 'GET_WIKIPEDIA_CONTENT_SUCCESS';
export const GET_WIKIPEDIA_CONTENT_ERROR = 'GET_WIKIPEDIA_CONTENT_ERROR';
