export const SELECTED_FILM = 'SELECTED_FILM';
export const SELECTED_SPECIES = 'SELECTED_SPECIES';
export const FIND_ALL_FILMS = 'FIND_ALL_FILMS';
export const FIND_ALL_FILMS_SUCCESS = 'FIND_ALL_FILMS_SUCCESS';
export const FIND_ALL_FILMS_ERROR = 'FIND_ALL_FILMS_ERROR';
